//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public Beneficiary()
        {
            this.Cards = new HashSet<Card>();
            this.PointsExchanges = new HashSet<PointsExchange>();
        }
    
        public int Id { get; set; }
        public int EducationalInstitutionId { get; set; }
        public int TownId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
    
        public virtual User User { get; set; }
        public virtual EducationalInstitution EducationalInstitution { get; set; }
        public virtual Town Town { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<PointsExchange> PointsExchanges { get; set; }
    }
}
