//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int BeneficiaryId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual Beneficiary Beneficiary { get; set; }
    }
}
