//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsExchange
    {
        public int Id { get; set; }
        public int PrizeId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime ExchangeDate { get; set; }
    
        public virtual Reward Reward { get; set; }
        public virtual Student Student { get; set; }
    }
}
