//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prize
    {
        public Prize()
        {
            this.PointsExchanges = new HashSet<PointsExchange>();
            this.SectionItems = new HashSet<SectionItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PointsNeeded { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageFileId { get; set; }
    
        public virtual ICollection<PointsExchange> PointsExchanges { get; set; }
        public virtual File File { get; set; }
        public virtual ICollection<SectionItem> SectionItems { get; set; }
    }
}
