//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public int ShopId { get; set; }
        public int CardId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
