//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    
    public partial class RptBenefitsUsed
    {
        public string Beneficiary { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Benefit { get; set; }
    }
}
