//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    
    public partial class RptGeneratedPoints
    {
        public string ShopName { get; set; }
        public string Beneficiary { get; set; }
        public string EducationalInstitutionName { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Points { get; set; }
        public string Beneficiary1 { get; set; }
    }
}
