//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionItem
    {
        public int Id { get; set; }
        public int SectionId { get; set; }
        public Nullable<int> BenefitId { get; set; }
        public Nullable<int> PrizeId { get; set; }
        public int Order { get; set; }
    
        public virtual Prize Prize { get; set; }
        public virtual Section Section { get; set; }
        public virtual Benefit Benefit { get; set; }
    }
}
