//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointEx.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PointExResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PointExResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointEx.Web.App_LocalResources.PointExResources", typeof(PointExResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Beneficiario.
        /// </summary>
        public static string BeneficiaryDetailTitle {
            get {
                return ResourceManager.GetString("BeneficiaryDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Beneficiario.
        /// </summary>
        public static string CreateBeneficiaryTitle {
            get {
                return ResourceManager.GetString("CreateBeneficiaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Beneficio.
        /// </summary>
        public static string CreateBenefitTitle {
            get {
                return ResourceManager.GetString("CreateBenefitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Sucursal.
        /// </summary>
        public static string CreateBranchOffice {
            get {
                return ResourceManager.GetString("CreateBranchOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Establecimiento Educativo.
        /// </summary>
        public static string CreateEducationalInstitutionTitle {
            get {
                return ResourceManager.GetString("CreateEducationalInstitutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Premio.
        /// </summary>
        public static string CreatePrizeTitle {
            get {
                return ResourceManager.GetString("CreatePrizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Compra.
        /// </summary>
        public static string CreatePurchaseTitle {
            get {
                return ResourceManager.GetString("CreatePurchaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Comercio.
        /// </summary>
        public static string CreateShopTitle {
            get {
                return ResourceManager.GetString("CreateShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Beneficio.
        /// </summary>
        public static string DetailBenefitTitle {
            get {
                return ResourceManager.GetString("DetailBenefitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Premio.
        /// </summary>
        public static string DetailPrizeTitle {
            get {
                return ResourceManager.GetString("DetailPrizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Beneficiario.
        /// </summary>
        public static string EditBeneficiaryTitle {
            get {
                return ResourceManager.GetString("EditBeneficiaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Beneficio.
        /// </summary>
        public static string EditBenefitTitle {
            get {
                return ResourceManager.GetString("EditBenefitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Sucursal.
        /// </summary>
        public static string EditBranchOffice {
            get {
                return ResourceManager.GetString("EditBranchOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Establecimiento Educativo.
        /// </summary>
        public static string EditEducationalInstitutionTitle {
            get {
                return ResourceManager.GetString("EditEducationalInstitutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Premio.
        /// </summary>
        public static string EditPrizeTitle {
            get {
                return ResourceManager.GetString("EditPrizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Comercio.
        /// </summary>
        public static string EditShopTitle {
            get {
                return ResourceManager.GetString("EditShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Establecimiento Educativo.
        /// </summary>
        public static string EducationalInstitutionDetailTitle {
            get {
                return ResourceManager.GetString("EducationalInstitutionDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Comercio.
        /// </summary>
        public static string ShopDetailTitle {
            get {
                return ResourceManager.GetString("ShopDetailTitle", resourceCulture);
            }
        }
    }
}
